Scoutpocket/Models/Database/ClubList.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Scoutpocket.Models.Database
{

    public class GroupBy<K, T>
    {
        public K Key;
        public IEnumerable<T> Values;
    }


    public class ClubList
    {

      
        public int ClubListID { get; set; }

        [DisplayName("Klubnavn")]
        public string ClubName { get; set; }
        
        [DisplayName("Klub billede")]
        public string ClubImage { get; set; }

        [NotMapped]
        public HttpPostedFileBase MyFile { get; set; }
        [NotMapped]
        public string CroppedImagePath { get; set; }


        //public Profile profile { get; set; }
        //public Club club { get; set; }

        //One to many relation
        public virtual ICollection<Player> Player { get; set; }



    }
}

Scoutpocket/Controllers/ClubListsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Scoutpocket.Models.Database;

namespace Scoutpocket.Controllers
{
    public class ClubListsController : Controller
    {
        private Connection db = new Connection();

        [Authorize(Roles = "1")]
        public ActionResult Index()
        {
            return View(db.ClubLists.ToList());
        }

        // GET: ClubLists/Details/5
        [Authorize(Roles = "1")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClubList clubList = db.ClubLists.Find(id);
            if (clubList == null)
            {
                return HttpNotFound();
            }
            return View(clubList);
        }


        // GET: ClubLists/Edit/5
        [Authorize(Roles = "1")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClubList clubList = db.ClubLists.Find(id);
            if (clubList == null)
            {
                return HttpNotFound();
            }
            return View(clubList);
        }

        // POST: ClubLists/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "1")]
        public ActionResult Edit([Bind(Include = "ClubListID, ClubImage, MyFile, CroppedImagePath")] ClubList clubList)
        {

            Connection connection = new Connection();
            //clubList.ClubListID

            var clublist = connection.ClubLists.SingleOrDefault(a => a.ClubListID == clubList.ClubListID);
            var getFileName = Session["getFileName"];

            clublist.ClubImage = clubList.ClubListID.ToString();

            connection.SaveChanges();

            return RedirectToAction("Edit");
        }
        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Scoutpocket/Views/ClubLists/Details.cshtml
@model Scoutpocket.Models.Database.ClubList

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Administration.cshtml";
}

<h2>Details</h2>

<div>
    <h4>ClubList</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ClubName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClubName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClubImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClubImage)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ClubListID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Scoutpocket/Views/ClubLists/Edit.cshtml
@model Scoutpocket.Models.Database.ClubList

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Administration.cshtml";
}


<!--Jquery-->
<script src="~/Scripts/jquery-3.2.0.min.js"></script>
<script src="~/Scripts/jquery-ui-1.9.2.min.js"></script>

<!--JCrop-->
<link href="~/Scripts/Jcrop/css/jquery.Jcrop.min.css" rel="stylesheet" />
<script src="~/Scripts/Jcrop/js/jquery.Jcrop.min.js"></script>

<!--File upload-->
<script src="~/Scripts/Jcrop/file-upload/jquery.iframe-transport.js"></script>
<script src="~/Scripts/Jcrop/file-upload/jquery.fileupload.js"></script>
<script src="~/Scripts/Jcrop/file-upload/jquery.fileupload-ui.js"></script>


<style>
    .button-place {
        margin: 0;
        text-align: center;
    }
    .btn-file {
        position: relative;
        overflow: hidden;
    }

    .btn-file input[type=file] {
        position: absolute;
        top: 0;
        right: 0;
        min-width: 100%;
        min-height: 100%;
        font-size: 100px;
        text-align: right;
        filter: alpha(opacity=0);
        opacity: 0;
        outline: none;
        background: white;
        cursor: inherit;
        display: block;
        }

    .jcrop-keymgr {
        display: none;
    }
</style>
<div class="container">
  

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>ClubList</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ClubListID)

            <div class="form-group">
                @Html.LabelFor(model => model.ClubImage, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ClubImage, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ClubImage, "", new { @class = "text-danger" })

                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>

            <div>
                <div class="button-place">

                    <button type="button" data-toggle="modal" data-target="#myModal" class="btn btn-success form-control" style="background:#f9c63b; border: none; font-size: 11pt; width:200px;">Upload profil billede</button>


                    <!-- Modal -->
                    <div id="myModal" class="modal fade" role="dialog">
                        <div class="modal-dialog">

                            <!-- Modal content-->
                            <div class="modal-content" style="color:black;">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">×</button>
                                    <h4 class="modal-title">Upload profil billede</h4>
                                </div>
                                <div class="modal-body">

                                    <p>1. Tryk på 'Upload billede'</p>
                                    <p>2. Tryk på 'Vis billede'</p>
                                    <p>3. Tryk på 'Gem billede'</p>

                                </div>

                                <div class="modal-footer">

                                    <style>
                                        #modal {
                                            position: absolute;
                                            background: black;
                                            width: 300px;
                                            height: 300px;
                                            display: none;
                                        }

                                        .preview-container {
                                            top: 100px;
                                            left: 80px;
                                            width: 150px;
                                            height: auto;
                                            background-color: #2185C5;
                                            position: relative;
                                        }

                                        #previewSub {
                                            width: 150px;
                                            height: auto; /* use auto here so it doesnt distort the aspect ratio of the image */
                                        }

                                        #abutton {
                                            position: absolute;
                                            background: red;
                                            top: 350px;
                                        }
                                    </style>

                                    <script>

                                        $('#abutton').on("click", function () {
                                            $("#modal").show();
                                            $('#previewSub').Jcrop();
                                        });
                                    </script>



                                    <div id="crop-image-area" style="display:none;">
                                        @*<a href="#" id="hl-crop-image">Crop Image</a>*@
                                        <img id="uploaded-image" class="img-responsive" src="#" />
                                        @*<img id="my-cropped-image" src="#" style="display:none;" />*@

                                    </div>







                                    @using (Html.BeginForm("SaveImage", "ClubLists"))
                                    {
                                        <div style="margin-top:20px;">

                                            <div class="btn btn-success btn-file col-md-3">


                                                <!-- it goes for the ClubList/edit/id form and not the saveimage-->
                                                <input value="Gem Billede" class="btn btn-default" type="submit">
                                            </div>



                                            <div class="btn btn-success btn-file col-md-3">

                                                <a href="#" id="hl-start-upload" style="color:white;">Vis billede </a>
                                            </div>
                                            <div class="btn btn-success btn-file col-md-3">
                                                Upload billede <input type="file" placeholder="Upload billede">
                                                @Html.TextBoxFor(model => model.MyFile, new { id = "fu-my-simple-upload", type = "file" })
                                            </div>


                                            @Html.Hidden("UploadedImagePath", string.Empty, new { id = "hf-uploaded-image-path" })
                                            @Html.HiddenFor(model => model.CroppedImagePath, new { id = "hf-cropped-image-path" })



                                        </div>




                                    }



                                </div>
                            </div>

                        </div>
                    </div>



                </div>
            </div>

        </div>
    }




</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


<script type="text/javascript">

    //************************************** JavaScript for ajax file upload **************************************
    var jqXHRData;

    $(document).ready(function () {

        'use strict';


        $('#fu-my-simple-upload').fileupload({
            url: '/File/UploadClubImage',
            dataType: 'json',
            add: function (e, data) {
                jqXHRData = data;
            },
            done: function (event, data) {
                if (data.result.isUploaded) {

                    $("#hf-uploaded-image-path").val(data.result.filePath);

                    destroyCrop();

                    $("#uploaded-image").attr("src", data.result.filePath + "?t=" + new Date().getTime());

                    initCrop();

                    $("#crop-image-area").fadeIn("slow");
                } else {

                }
            },
            fail: function (event, data) {
                if (data.files[0].error) {
                    alert(data.files[0].error);
                }
            }
        });
    });

    $("#hl-start-upload").on('click', function () {
        if (jqXHRData) {
            jqXHRData.submit();
        }
        return false;
    });
    //************************************** JavaScript for ajax file upload END **************************************



    //************************************** JavaScript for cropping of image *****************************************
    var imageCropWidth = 0;
    var imageCropHeight = 0;
    var cropPointX = 0;
    var cropPointY = 0;

    $("#hl-crop-image").on("click", function (e) {
        e.preventDefault();
        cropImage();
    });

    function initCrop() {
        $('#uploaded-image').Jcrop({
            onChange: setCoordsAndImgSize,
            aspectRatio: 1
        });
    }

    function destroyCrop() {
        var jcropApi = $('#uploaded-image').data('Jcrop');

        if (jcropApi !== undefined) {
            jcropApi.destroy();
            $('#uploaded-image').attr('style', "").attr("src", "");
        }
    }

    function setCoordsAndImgSize(e) {

        imageCropWidth = e.w;
        imageCropHeight = e.h;

        cropPointX = e.x;
        cropPointY = e.y;
    }

    function cropImage() {

        if (imageCropWidth == 0 && imageCropHeight == 0) {
            alert("Please select crop area.");
            return;
        }

        $.ajax({
            url: '/Image/CropImage',
            type: 'POST',
            data: {
                imagePath: $("#hf-uploaded-image-path").val(),
                cropPointX: cropPointX,
                cropPointY: cropPointY,
                imageCropWidth: imageCropWidth,
                imageCropHeight: imageCropHeight
            },
            success: function (data) {

                $("#hf-cropped-image-path").val(data.photoPath);

                $("#my-cropped-image")
                    .attr("src", data.photoPath + "?t=" + new Date().getTime())
                    .show();

                $("#btn-my-submit").fadeIn("slow");
            },
            error: function (data) { }
        });
    }

    //************************************** JavaScript for cropping of image END **************************************

</script>

Scoutpocket/Views/ClubLists/Index.cshtml
@model IEnumerable<Scoutpocket.Models.Database.ClubList>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Administration.cshtml";
}



<div class="continer">

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ClubName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ClubImage)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ClubName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ClubImage)
                </td>
                <td>
                    @Html.ActionLink("Rediger", "Edit", new { id = item.ClubListID }) 



                </td>
            </tr>
        }

    </table>


</div>